name: WeenSpace CLI login
description: WeenSpace CLI login to staging WeenSpace Cloud
inputs:
  token:
    description: "Cloud access token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Write config file
      shell: bash
      id: write-config-file
      env:
        ACCESS_TOKEN: ${{ inputs.token }}
      run: |
        jq --null-input \
           --arg token "Token $ACCESS_TOKEN" \
           '{"token":$token,"telemetry":"false","weenspace_env":"staging","cloud_api_url":"https://staging-cloud.weenspace.come/platform/api","organization_slug":"weenspace","organization_name":"WeenSpace"}' > ~/.config/weenspace.json
